name: nuget build (nupkg) checks

on:
  workflow_dispatch:
    inputs:
      vcVersions:
        description: "Visual C Compiler Version"
        required: true
        default: "vc16"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Build nuspec and targets
        run: |
          cd platforms/nuget
          mkdir build
          python build-jinja.py --package_version "${{ github.event.inputs.vcVersions }}" --build_directory "D:\a\opencv\build\install" 
     