name: nuget build checks

on:
  workflow_dispatch:
    inputs:
      vcVersions:
        description: "Visual C Compiler Version"
        required: true
        default: "vc16"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set vc14
        if: "${{ github.event.inputs.vcVersions == 'vc14' }}"
        run: |
          $CMAKE_GENERATOR_OPTIONS="Visual Studio 14 2017"
      