name: nuget build checks

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency packages
      run: |
        choco install ninja cmake
        ninja --version
        cmake --version

    - name: Configure
      run: |
        $CMAKE_GENERATOR_OPTIONS="Visual Studio 16 2019"

        $RepoSource="../opencv"
        mkdir build
        cd build

        cmake "${CMAKE_GENERATOR_OPTIONS[@]}" "${(-DBUILD_PERF_TESTS:BOOL=OFF -DBUILD_TESTS:BOOL=OFF -DBUILD_DOCS:BOOL=OFF -DWITH_CUDA:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DINSTALL_CREATE_DISTRIB=ON)}" -S "D:/a/opencv/opencv" -B "D:/a/opencv/build"
        
        cmake --build ''  --config debug
        cmake --build ''  --target install --config debug

    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: "D:/a/opencv/build"