name: nuget build checks

on:
  workflow_dispatch:
    inputs:
      vcVersions:
        description: "Visual C Compiler Version"
        required: true
        default: "vc16"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache OpenCV Build
        id: cache-opencv-build
        uses: actions/cache@v2
        with:
          path: opencv-build
          key: ${{ runner.os }}-opencv-build
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - name: Install dependency packages
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version
          python -m pip install --upgrade pip
          pip install jinja2
      - name: Build nuspec and targets
        run: |
          cd platforms/nuget
          mkdir build
          python build-targets.py
          python build-jinja.py --package_version "${{ github.event.inputs.vcVersions }}" --build_directory "D:\a\opencv\opencv\"
      - name: Build world DLLs
        run: |
          $CMAKE_GENERATOR_OPTIONS="Visual Studio 16 2019"
          cd "D:/a/opencv/"
          mkdir build
          cd build
          cmake "${CMAKE_GENERATOR_OPTIONS[@]}" "-DBUILD_opencv_world:BOOL=ON" -S "D:/a/opencv/opencv" -B "D:/a/opencv/build"

          cmake --build "D:/a/opencv/build" --config Debug --target install
          # cmake --build "D:/a/opencv/build" --config Release
      - name: Build shared libs
        run: |
          cmake "${CMAKE_GENERATOR_OPTIONS[@]}" "-DBUILD_SHARED_LIBS=ON" -S "D:/a/opencv/opencv" -B "D:/a/opencv/build"

          # cmake --build "D:/a/opencv/build" --config Debug
          # cmake --build "D:/a/opencv/build" --config Release
      - name: Build nupkg
        run: |
          cd platforms/nuget/build
          mkdir nupkg
          # nuget pack opencv.nuspec -OutputDirectory nupkg
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: |
            D:/a/opencv/
