name: nuget build checks

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency packages
      run: |
        choco install ninja cmake
        ninja --version
        cmake --version

    - name: Configure
      run: |
        $CMAKE_GENERATOR_OPTIONS="Visual Studio 16 2019"

        $RepoSource="../opencv"
        mkdir build
        cd build

        cmake "${CMAKE_GENERATOR_OPTIONS[@]}" "-DBUILD_opencv_world:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON" -S "D:/a/opencv/opencv" -B "D:/a/opencv/build"
        
        cmake --build "D:/a/opencv/build" --config Debug

    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        title: assets-for-download
          - files: [ "D:/a/opencv/build/bin/", "D:/a/opencv/build/lib/" ]
